{"uninstall": {"ipfs": false, "ipget": false, "cluster_follow": false}, "error": "Traceback (most recent call last):\n  File \"C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\install_ipfs.py\", line 2006, in test\n    results[\"install\"] = this_install_ipfs.install_and_configure()\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\install_ipfs.py\", line 1987, in install_and_configure\n    cluster_follow_config = self.config_ipfs_cluster_follow(cluster_name = self.cluster_name, ipfs_path =  self.ipfs_path)\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\install_ipfs.py\", line 1147, in config_ipfs_cluster_follow\n    if int(find_daemon_results) > 0:\n           ^^^^^^^^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'find_daemon_results' where it is not associated with a value\ncannot access local variable 'find_daemon_results' where it is not associated with a value2006"}