{"uninstall": {"ipfs": false, "ipget": false, "cluster_service": false, "cluster_ctl": false}, "error": "Traceback (most recent call last):\n  File \"C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\install_ipfs.py\", line 2460, in test\n    results[\"install\"] = this_install_ipfs.install_and_configure()\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\install_ipfs.py\", line 2428, in install_and_configure\n    cluster_service  = self.install_ipfs_cluster_service()\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\install_ipfs.py\", line 812, in install_ipfs_cluster_service\n    results = subprocess.check_output(command, shell=True)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\barberb\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\subprocess.py\", line 466, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\barberb\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\subprocess.py\", line 571, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command 'wget https://dist.ipfs.tech/ipfs-cluster-service/v1.1.2/ipfs-cluster-service_v1.1.2_windows-amd64.zip -O C:\\Users\\barberb\\AppData\\Local\\Temp\\tmpuptt7t3m.tar.gz' returned non-zero exit status 1.\nCommand 'wget https://dist.ipfs.tech/ipfs-cluster-service/v1.1.2/ipfs-cluster-service_v1.1.2_windows-amd64.zip -O C:\\Users\\barberb\\AppData\\Local\\Temp\\tmpuptt7t3m.tar.gz' returned non-zero exit status 1.2460"}