{"uninstall": {"ipfs": false, "ipget": false, "cluster_follow": false}, "error": "Traceback (most recent call last):\n  File \"C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\install_ipfs.py\", line 1838, in test\n    results[\"install\"] = this_install_ipfs.install_and_configure()\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\install_ipfs.py\", line 1798, in install_and_configure\n    ipfs_config = self.config_ipfs(cluster_name = self.cluster_name, ipfs_path = self.ipfs_path)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\install_ipfs.py\", line 1260, in config_ipfs\n    find_daemon_results = subprocess.check_output(find_daemon_cmd, shell=True)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\barberb\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\subprocess.py\", line 466, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\barberb\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\subprocess.py\", line 571, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command 'ps -ef | grep ipfs | grep daemon | grep -v grep | wc -l' returned non-zero exit status 255.\nCommand 'ps -ef | grep ipfs | grep daemon | grep -v grep | wc -l' returned non-zero exit status 255.1838"}