{
  "success": false,
  "tests": {
    "connection": {
      "success": false,
      "operation": "check_connection",
      "timestamp": 1744273208.073364,
      "correlation_id": "1c9d8bef-5dfa-4dfe-8ca3-09045bfe6f67",
      "duration_ms": 0.7505416870117188,
      "error": "Failed to connect to Lotus API: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /rpc/v0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x720055bcdd60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "error_type": "LotusConnectionError"
    }
  },
  "timestamp": 1744273208.0730681,
  "error": "Failed to connect to Lotus API: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /rpc/v0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x720055bcdd60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
  "error_type": "LotusConnectionError"
}